// Generated by jextract

package dev.diplomattest.somelib.ntv;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct BorrowedFields {
 *     DiplomatString16View a;
 *     DiplomatStringView b;
 *     DiplomatStringView c;
 * }
 * }
 */
public class BorrowedFields {

    BorrowedFields() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        DiplomatString16View.layout().withName("a"),
        DiplomatStringView.layout().withName("b"),
        DiplomatStringView.layout().withName("c")
    ).withName("BorrowedFields");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout a$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("a"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DiplomatString16View a
     * }
     */
    public static final GroupLayout a$layout() {
        return a$LAYOUT;
    }

    private static final long a$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DiplomatString16View a
     * }
     */
    public static final long a$offset() {
        return a$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DiplomatString16View a
     * }
     */
    public static MemorySegment a(MemorySegment struct) {
        return struct.asSlice(a$OFFSET, a$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DiplomatString16View a
     * }
     */
    public static void a(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, a$OFFSET, a$LAYOUT.byteSize());
    }

    private static final GroupLayout b$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("b"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DiplomatStringView b
     * }
     */
    public static final GroupLayout b$layout() {
        return b$LAYOUT;
    }

    private static final long b$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DiplomatStringView b
     * }
     */
    public static final long b$offset() {
        return b$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DiplomatStringView b
     * }
     */
    public static MemorySegment b(MemorySegment struct) {
        return struct.asSlice(b$OFFSET, b$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DiplomatStringView b
     * }
     */
    public static void b(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, b$OFFSET, b$LAYOUT.byteSize());
    }

    private static final GroupLayout c$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("c"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DiplomatStringView c
     * }
     */
    public static final GroupLayout c$layout() {
        return c$LAYOUT;
    }

    private static final long c$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DiplomatStringView c
     * }
     */
    public static final long c$offset() {
        return c$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DiplomatStringView c
     * }
     */
    public static MemorySegment c(MemorySegment struct) {
        return struct.asSlice(c$OFFSET, c$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DiplomatStringView c
     * }
     */
    public static void c(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, c$OFFSET, c$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

