// Generated by jextract

package dev.diplomattest.somelib.ntv;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct BorrowedFieldsWithBounds {
 *     DiplomatString16View field_a;
 *     DiplomatStringView field_b;
 *     DiplomatStringView field_c;
 * }
 * }
 */
public class BorrowedFieldsWithBounds {

    BorrowedFieldsWithBounds() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        DiplomatString16View.layout().withName("field_a"),
        DiplomatStringView.layout().withName("field_b"),
        DiplomatStringView.layout().withName("field_c")
    ).withName("BorrowedFieldsWithBounds");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout field_a$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("field_a"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DiplomatString16View field_a
     * }
     */
    public static final GroupLayout field_a$layout() {
        return field_a$LAYOUT;
    }

    private static final long field_a$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DiplomatString16View field_a
     * }
     */
    public static final long field_a$offset() {
        return field_a$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DiplomatString16View field_a
     * }
     */
    public static MemorySegment field_a(MemorySegment struct) {
        return struct.asSlice(field_a$OFFSET, field_a$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DiplomatString16View field_a
     * }
     */
    public static void field_a(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, field_a$OFFSET, field_a$LAYOUT.byteSize());
    }

    private static final GroupLayout field_b$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("field_b"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DiplomatStringView field_b
     * }
     */
    public static final GroupLayout field_b$layout() {
        return field_b$LAYOUT;
    }

    private static final long field_b$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DiplomatStringView field_b
     * }
     */
    public static final long field_b$offset() {
        return field_b$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DiplomatStringView field_b
     * }
     */
    public static MemorySegment field_b(MemorySegment struct) {
        return struct.asSlice(field_b$OFFSET, field_b$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DiplomatStringView field_b
     * }
     */
    public static void field_b(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, field_b$OFFSET, field_b$LAYOUT.byteSize());
    }

    private static final GroupLayout field_c$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("field_c"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DiplomatStringView field_c
     * }
     */
    public static final GroupLayout field_c$layout() {
        return field_c$LAYOUT;
    }

    private static final long field_c$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DiplomatStringView field_c
     * }
     */
    public static final long field_c$offset() {
        return field_c$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DiplomatStringView field_c
     * }
     */
    public static MemorySegment field_c(MemorySegment struct) {
        return struct.asSlice(field_c$OFFSET, field_c$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DiplomatStringView field_c
     * }
     */
    public static void field_c(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, field_c$OFFSET, field_c$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

