// Generated by jextract

package dev.diplomattest.somelib.ntv;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ImportedStruct {
 *     UnimportedEnum foo;
 *     uint8_t count;
 * }
 * }
 */
public class ImportedStruct {

    ImportedStruct() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        somelib_h.C_INT.withName("foo"),
        somelib_h.C_CHAR.withName("count"),
        MemoryLayout.paddingLayout(3)
    ).withName("ImportedStruct");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt foo$LAYOUT = (OfInt)$LAYOUT.select(groupElement("foo"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UnimportedEnum foo
     * }
     */
    public static final OfInt foo$layout() {
        return foo$LAYOUT;
    }

    private static final long foo$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UnimportedEnum foo
     * }
     */
    public static final long foo$offset() {
        return foo$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UnimportedEnum foo
     * }
     */
    public static int foo(MemorySegment struct) {
        return struct.get(foo$LAYOUT, foo$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UnimportedEnum foo
     * }
     */
    public static void foo(MemorySegment struct, int fieldValue) {
        struct.set(foo$LAYOUT, foo$OFFSET, fieldValue);
    }

    private static final OfByte count$LAYOUT = (OfByte)$LAYOUT.select(groupElement("count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t count
     * }
     */
    public static final OfByte count$layout() {
        return count$LAYOUT;
    }

    private static final long count$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t count
     * }
     */
    public static final long count$offset() {
        return count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t count
     * }
     */
    public static byte count(MemorySegment struct) {
        return struct.get(count$LAYOUT, count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t count
     * }
     */
    public static void count(MemorySegment struct, byte fieldValue) {
        struct.set(count$LAYOUT, count$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

