headers = [
    "",
    "#include \"mozilla/Maybe.h\"",
    "#include \"mozilla/UniquePtr.h\"",
    "#include \"mozilla/Span.h\"",
]

[nullopt]
name = "mozilla::Nothing"
expr = "mozilla::Nothing"
is_call = true

[optional]
name = "mozilla::Maybe"
expr = "mozilla::Maybe"

[someopt]
name = "mozilla::Some"
expr = "mozilla::Some"
is_call = true

[span]
name = "mozilla::Span"
expr = "mozilla::Span"

[string_view]
name = "mozilla::Span"
expr = "mozilla::Span<const char>"

[string_view16]
name = "mozilla::Span"
expr = "mozilla::Span<const char16_t>"

[unique_ptr]
name = "mozilla::UniquePtr"
expr = "mozilla::UniquePtr"
