// ignore_for_file: non_constant_identifier_names, experimental_member_use, unused_element
// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

enum FixedDecimalGroupingStrategy {
  /// Auto grouping
  auto,
  /// No grouping
  never,
  /// Always group
  always,
  /// At least 2 groups
  min2;

}

// dart format on
