// generated by diplomat-tool

part of 'lib.g.dart';

enum ICU4XFixedDecimalGroupingStrategy {
  /// Auto grouping
  auto,

  /// No grouping
  never,

  /// Always group
  always,

  /// At least 2 groups
  min2;
}
