// generated by diplomat-tool

import type { ICU4XFixedDecimalGroupingStrategy } from "./ICU4XFixedDecimalGroupingStrategy"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";

export class ICU4XFixedDecimalFormatterOptions {
    #groupingStrategy;
    get groupingStrategy() : ICU4XFixedDecimalGroupingStrategy;
    set groupingStrategy(value: ICU4XFixedDecimalGroupingStrategy); 
    #someOtherConfig;
    get someOtherConfig() : boolean;
    set someOtherConfig(value: boolean); 

    static default_(): ICU4XFixedDecimalFormatterOptions;

    

}