// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";


/** An ICU4X Locale, capable of representing strings like `"en-US"`.
*
*See the [Rust documentation for `Locale`](https://docs.rs/icu/latest/icu/locid/struct.Locale.html) for more information.
*/

const ICU4XLocale_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.ICU4XLocale_destroy(ptr);
});
export class ICU4XLocale {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];
    
    
    constructor(ptr, selfEdge) {
        
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;
        // Unconditionally register to destroy when this object is ready to garbage collect.
        ICU4XLocale_box_destroy_registry.register(this, this.#ptr);
    }

    get ffiValue() {
        return this.#ptr;
    }


    static new_(name) {
        
        const nameSlice = diplomatRuntime.DiplomatBuf.str8(wasm, name);
        const result = wasm.ICU4XLocale_new(nameSlice.ptr, nameSlice.size);
    
        try {
    
            return new ICU4XLocale(result, []);
        } finally {
        
            nameSlice.free();
        
        }
    }

    

}