mod filters;

use std::io;

use askama::Template;
use clap::{Parser, Subcommand};
use diplomat_core::hir::BackendAttrSupport;
use mdbook_preprocessor::errors::Result;
use mdbook_preprocessor::Preprocessor;
use minijinja::{context, Environment};

#[derive(Debug, Subcommand)]
enum Supports {
    Supports {
        #[arg()]
        renderer: String,
    },
}

#[derive(Debug, Parser)]
#[clap(name = "mdbook-diplomat", about = "Diplomat mdbook preprocessor")]
struct Opt {
    #[command(subcommand)]
    supports: Option<Supports>,
}

fn main() {
    let opt = Opt::parse();

    if opt.supports.is_some() {
        return;
    }

    handle_preprocessing().expect("Could not preprocess book");
}

struct DiplomatPreprocessor;

/// Backends the book's per-attribute support lists cover.
///
/// Sourced from the tool so a newly added backend cannot be forgotten here.
const LANGUAGES: &[&str] = diplomat_tool::TARGET_LANGUAGES;

/// Backends held out of those lists even though the tool supports them.
///
/// `dotnet` was already missing from every rendered support block before the Safe
/// Rust backend existed. Including the tool's full target list would change all of
/// those blocks at once, so it is left out here as a separate question rather than
/// decided in passing.
const UNLISTED_LANGUAGES: &[&str] = &["dotnet"];

/// The languages the book renders support lists for: the tool's targets minus
/// [`UNLISTED_LANGUAGES`].
fn book_languages() -> impl Iterator<Item = &'static str> {
    LANGUAGES
        .iter()
        .copied()
        .filter(|language| !UNLISTED_LANGUAGES.contains(language))
}

impl DiplomatPreprocessor {
    fn generate_language_supports(language: &str) -> String {
        #[derive(Template)]
        #[template(path = "supports.md.jinja")]
        struct SupportsBlock {
            attr_support: BackendAttrSupport,
        }
        SupportsBlock {
            attr_support: diplomat_tool::get_supported(language),
        }
        .render()
        .expect("Could not render supports block.")
    }

    fn get_which_languages_supports(attr: &str) -> String {
        let mut language_list = Vec::new();
        for l in book_languages() {
            let supports = diplomat_tool::get_supported(l);
            if supports.check_string(attr).unwrap_or(false) {
                language_list.push(l);
            }
        }

        #[derive(Template)]
        #[template(path = "supported_by.md.jinja")]
        struct LanguagesSupported<'a> {
            languages: Vec<&'a str>,
            supports_query: &'a str,
        }

        LanguagesSupported {
            languages: language_list,
            supports_query: attr,
        }
        .render()
        .expect("Could not render languages that this is supported by.")
    }
}

impl Preprocessor for DiplomatPreprocessor {
    fn name(&self) -> &str {
        "mdbook-diplomat"
    }

    fn run(
        &self,
        _ctx: &mdbook_preprocessor::PreprocessorContext,
        mut book: mdbook_preprocessor::book::Book,
    ) -> mdbook_preprocessor::errors::Result<mdbook_preprocessor::book::Book> {
        let mut env = Environment::new();
        env.add_function("supports", Self::generate_language_supports);
        env.add_function("get_supports", Self::get_which_languages_supports);
        // Evaluate each page as an askama template:
        book.for_each_chapter_mut(|ch| {
            let expr = env
                .template_from_named_str(&ch.name, &ch.content)
                .expect("Could not compile book expression.");
            ch.content = expr
                .render(context! {})
                .expect("Could not render template.");
        });
        Ok(book)
    }
}

fn handle_preprocessing() -> Result<()> {
    let pre = DiplomatPreprocessor;
    let (ctx, book) = mdbook_preprocessor::parse_input(io::stdin())?;

    let processed_book = pre.run(&ctx, book)?;
    serde_json::to_writer(io::stdout(), &processed_book)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Languages named in a rendered `get_supports` list, in order.
    fn rendered_languages(attr: &str) -> Vec<String> {
        DiplomatPreprocessor::get_which_languages_supports(attr)
            .split('`')
            .skip(1)
            .step_by(2)
            .filter(|name| diplomat_tool::TARGET_LANGUAGES.contains(name))
            .map(|name| name.to_string())
            .collect()
    }

    /// The Safe Rust backend is generated by the tool and must therefore appear in
    /// the book's support lists for the attributes it declares. `dotnet` must stay
    /// out — see [`UNLISTED_LANGUAGES`]. Pinned verbatim so either drift is loud.
    #[test]
    fn rust_is_listed_and_dotnet_is_not() {
        assert_eq!(
            rendered_languages("option"),
            ["c", "cpp", "dart", "demo_gen", "js", "kotlin", "nanobind", "rust"]
        );
    }

    /// Every backend that reports support for an attribute must appear in the
    /// rendered "supported by" list. The list used to be a hand-maintained array, so
    /// it silently drifted away from the tool's real backends.
    #[test]
    fn supported_by_list_matches_the_tool() {
        for attr in ["option", "static_slices", "constructors", "callbacks"] {
            for language in book_languages() {
                if diplomat_tool::get_supported(language)
                    .check_string(attr)
                    .unwrap_or(false)
                {
                    assert!(
                        rendered_languages(attr).iter().any(|l| l == language),
                        "{language} supports `{attr}` but is missing from the rendered list"
                    );
                }
            }
        }
    }
}
