// generated by diplomat-tool
import type { OpaqueThin } from "./OpaqueThin"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class OpaqueThinIter {
    /** @internal */
    get ffiValue(): pointer;


    next(): IteratorResult<OpaqueThin>;
}