// generated by diplomat-tool
import type { RenamedOpaqueIterator } from "./RenamedOpaqueIterator"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class RenamedOpaqueIterable {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    [Symbol.iterator](): RenamedOpaqueIterator;
}