name: feature_tests

publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  code_assets: ^0.19.8
  ffi: ^2.0.0
  hooks: ^0.20.4
  meta: ^1.12.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.21.0
