// generated by diplomat-tool

import { AttrEnum } from "./AttrEnum.mjs"
import { Unnamespaced } from "./Unnamespaced.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";




const AttrOpaque1_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.namespace_AttrOpaque1_destroy(ptr);
});

export class AttrOpaque1 {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];
    
    
    constructor(ptr, selfEdge) {
        
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;
        // Unconditionally register to destroy when this object is ready to garbage collect.
        AttrOpaque1_box_destroy_registry.register(this, this.#ptr);
    }

    get ffiValue() {
        return this.#ptr;
    }

    // Size of our opaque type in bytes for diplomat_alloc.
    // See https://doc.rust-lang.org/reference/type-layout.html for further reference.
    static get _size() {
        return 4;
    }
    
    // Alignment of our opaque type in bytes for diplomat_alloc.
    // See https://doc.rust-lang.org/reference/type-layout.html for further reference.
    static get _align() {
        return 4;
    }


    static new_() {
        
        const diplomat_recieve_buffer = wasm.diplomat_alloc(AttrOpaque1._size, AttrOpaque1._align);
        const result = wasm.namespace_AttrOpaque1_new(diplomat_recieve_buffer);
    
        const finalOut = new AttrOpaque1(diplomat_recieve_buffer, []);
        
        
        wasm.diplomat_free(diplomat_recieve_buffer, AttrOpaque1._size, AttrOpaque1._align);
        
    
        return finalOut;
    }

    get method() {
        const result = wasm.namespace_AttrOpaque1_method(this.ffiValue);
    
        const finalOut = result;
        
        
    
        return finalOut;
    }

    get abirenamed() {
        const result = wasm.renamed_on_abi_only(this.ffiValue);
    
        const finalOut = result;
        
        
    
        return finalOut;
    }

    methodDisabledcpp() {
        wasm.namespace_AttrOpaque1_method_disabledcpp(this.ffiValue);
    
        
        
    
    }

    useUnnamespaced(un) {
        wasm.namespace_AttrOpaque1_use_unnamespaced(this.ffiValue, un.ffiValue);
    
        
        
    
    }

    useNamespaced(n) {
        wasm.namespace_AttrOpaque1_use_namespaced(this.ffiValue, n.ffiValue);
    
        
        
    
    }

    

}