// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs"
import * as diplomatRuntime from "./diplomat-runtime.mjs"



export class AttrOpaque1 {
    

    get ffiValue(): pointer;


    static new_(): AttrOpaque1;

    get method(): number;

    get abirenamed(): number;

    methodDisabledcpp(): void;

    useUnnamespaced(un: Unnamespaced): void;

    useNamespaced(n: AttrEnum): void;

    

}