// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs"
import * as diplomatRuntime from "./diplomat-runtime.mjs"


export class BorrowedFieldsWithBounds {
	fieldA;
	fieldB;
	fieldC;

	
	// Return this struct as any array that can be expanded with spread syntax (...)
	#intoFFI() {
		[
			/*TODO: struct Slice fields*/, 
			/*TODO: struct Slice fields*/, 
			/*TODO: struct Slice fields*/]
	}

	
}