// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs"
import * as diplomatRuntime from "./diplomat-runtime.mjs"


export class BorrowedFields {
    a: String;
    b: String;
    c: String;
    static fromBarAndStrings(bar: Bar, dstr16: String, utf8Str: String): BorrowedFields;

    

}