// generated by diplomat-tool
import type { CyclicStructB } from "./CyclicStructB"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";

export class CyclicStructA {
    #a;
    get a() : CyclicStructB;
    set a(value: CyclicStructB); 

    static getB(): CyclicStructB;

    

}