// generated by diplomat-tool

import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";

export class ErrorStruct {
    #i;
    get i() : number;
    set i(value: number); 
    #j;
    get j() : number;
    set j(value: number); 

    

}