// generated by diplomat-tool
import type { pointer, char } from "./diplomat-runtime.d.ts";

export class ErrorStruct {
    #i;
    get i() : number;
    set i(value: number); 
    #j;
    get j() : number;
    set j(value: number); 

    

}