// generated by diplomat-tool

import type { Bar } from "./Bar"
import type { BorrowedFields } from "./BorrowedFields"
import type { BorrowedFieldsReturning } from "./BorrowedFieldsReturning"
import type { BorrowedFieldsWithBounds } from "./BorrowedFieldsWithBounds"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";



export class Foo {
    

    get ffiValue(): pointer;

    // Size of our opaque type in bytes for diplomat_alloc.
    // See https://doc.rust-lang.org/reference/type-layout.html for further reference.
    static get _size(): usize;
    
    // Alignment of our opaque type in bytes for diplomat_alloc.
    // See https://doc.rust-lang.org/reference/type-layout.html for further reference.
    static get _align(): usize;


    static new_(x: String): Foo;

    get bar(): Bar;

    static newStatic(x: String): Foo;

    asReturning(): BorrowedFieldsReturning;

    static extractFromFields(fields: BorrowedFields): Foo;

    static extractFromBounds(bounds: BorrowedFieldsWithBounds, anotherString: String): Foo;

    

}