// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs"
import * as diplomatRuntime from "./diplomat-runtime.mjs"


export class MyIterable {
	
	
	static new(x) {
        const result = wasm.namespace_MyIterable_new();
        return new MyIterable(result, []);;
    }
	
	iter() {
        const result = wasm.namespace_MyIterable_iter();
        return new MyIterator(result, [], aEdges);;
    }
	
}