// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs"
import * as diplomatRuntime from "./diplomat-runtime.mjs"



export class MyIterator {
    

    get ffiValue(): pointer;


    #iteratorNext(): number?;

    
    #value: number;
    
    get value: number;() {
    	return this.#value;
    }
    
    next() {
    	const out = this.#iteratorNext();
    
    	this.#value = out;
    
    	return out;
    }


}