// generated by diplomat-tool

import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";




const MyString_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.MyString_destroy(ptr);
});

export class MyString {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];
    
    
    constructor(ptr, selfEdge) {
        
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;
        // Unconditionally register to destroy when this object is ready to garbage collect.
        MyString_box_destroy_registry.register(this, this.#ptr);
    }

    get ffiValue() {
        return this.#ptr;
    }

    // Size of our opaque type in bytes for diplomat_alloc.
    // See https://doc.rust-lang.org/reference/type-layout.html for further reference.
    static get _size() {
        return 4;
    }
    
    // Alignment of our opaque type in bytes for diplomat_alloc.
    // See https://doc.rust-lang.org/reference/type-layout.html for further reference.
    static get _align() {
        return 4;
    }


    static new_(v) {
        
        const vSlice = diplomatRuntime.DiplomatBuf.str8(wasm, v);
        
        const diplomat_recieve_buffer = wasm.diplomat_alloc(MyString._size, MyString._align);
        const result = wasm.MyString_new(diplomat_recieve_buffer, vSlice.ptr, vSlice.size);
    
        const finalOut = new MyString(diplomat_recieve_buffer, []);
        
        
        vSlice.free();
        
        wasm.diplomat_free(diplomat_recieve_buffer, MyString._size, MyString._align);
        
    
        return finalOut;
    }

    static newUnsafe(v) {
        
        const vSlice = diplomatRuntime.DiplomatBuf.str8(wasm, v);
        
        const diplomat_recieve_buffer = wasm.diplomat_alloc(MyString._size, MyString._align);
        const result = wasm.MyString_new_unsafe(diplomat_recieve_buffer, vSlice.ptr, vSlice.size);
    
        const finalOut = new MyString(diplomat_recieve_buffer, []);
        
        
        vSlice.free();
        
        wasm.diplomat_free(diplomat_recieve_buffer, MyString._size, MyString._align);
        
    
        return finalOut;
    }

    static newOwned(v) {
        
        const vSlice = diplomatRuntime.DiplomatBuf.str8(wasm, v);
        
        const diplomat_recieve_buffer = wasm.diplomat_alloc(MyString._size, MyString._align);
        const result = wasm.MyString_new_owned(diplomat_recieve_buffer, vSlice.ptr, vSlice.size);
    
        const finalOut = new MyString(diplomat_recieve_buffer, []);
        
        
        wasm.diplomat_free(diplomat_recieve_buffer, MyString._size, MyString._align);
        
    
        return finalOut;
    }

    static newFromFirst(v) {
        
        const vSlice = diplomatRuntime.DiplomatBuf.str8(wasm, v);
        
        const diplomat_recieve_buffer = wasm.diplomat_alloc(MyString._size, MyString._align);
        const result = wasm.MyString_new_from_first(diplomat_recieve_buffer, vSlice.ptr, vSlice.size);
    
        const finalOut = new MyString(diplomat_recieve_buffer, []);
        
        
        vSlice.free();
        
        wasm.diplomat_free(diplomat_recieve_buffer, MyString._size, MyString._align);
        
    
        return finalOut;
    }

    set str(newStr) {
        
        const newStrSlice = diplomatRuntime.DiplomatBuf.str8(wasm, newStr);
        wasm.MyString_set_str(this.ffiValue, newStrSlice.ptr, newStrSlice.size);
    
        
        
        newStrSlice.free();
        
    
    }

    get str() {
        wasm.MyString_get_str(this.ffiValue);
    
        return writeable;
        
        
    
        return finalOut;
    }

    getBoxedStr() {
        const result = wasm.MyString_get_boxed_str(this.ffiValue);
    
        const finalOut = result // TODO: Slice c_to_js;
        
        
    
        return finalOut;
    }

    

}