// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs"
import * as diplomatRuntime from "./diplomat-runtime.mjs"



export class MyString {
    

    get ffiValue(): pointer;


    constructor(v: String): MyString;

    static unsafe(v: String): MyString;

    static newOwned(v: String): MyString;

    static newFromFirst(v: Array<String>): MyString;

    set str(newStr: String): void;

    get str(): String;

    getBoxedStr(): String;

}