// generated by diplomat-tool
import type { ImportedStruct } from "./ImportedStruct"
import type { MyStruct } from "./MyStruct"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";

export class Opaque {
    

    get ffiValue(): pointer;


    static new_(): Opaque;

    static tryFromUtf8(input: string): Opaque | undefined;

    static fromStr(input: string): Opaque;

    getDebugStr(): string;

    assertStruct(s: MyStruct);

    static returnsUsize(): number;

    static returnsImported(): ImportedStruct;

    static cmp(): number;

    

}