// generated by diplomat-tool

import { Utf16Wrap } from "./Utf16Wrap.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";




const OpaqueMutexedString_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.OpaqueMutexedString_destroy(ptr);
});

export class OpaqueMutexedString {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];
    
    
    constructor(ptr, selfEdge) {
        
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;
        // Unconditionally register to destroy when this object is ready to garbage collect.
        OpaqueMutexedString_box_destroy_registry.register(this, this.#ptr);
    }

    get ffiValue() {
        return this.#ptr;
    }

    // Size of our opaque type in bytes for diplomat_alloc.
    // See https://doc.rust-lang.org/reference/type-layout.html for further reference.
    static get _size() {
        return 4;
    }
    
    // Alignment of our opaque type in bytes for diplomat_alloc.
    // See https://doc.rust-lang.org/reference/type-layout.html for further reference.
    static get _align() {
        return 4;
    }


    static fromUsize(number) {
        
        const diplomat_recieve_buffer = wasm.diplomat_alloc(OpaqueMutexedString._size, OpaqueMutexedString._align);
        const result = wasm.OpaqueMutexedString_from_usize(diplomat_recieve_buffer, number);
    
        const finalOut = new OpaqueMutexedString(diplomat_recieve_buffer, []);
        
        
        wasm.diplomat_free(diplomat_recieve_buffer, OpaqueMutexedString._size, OpaqueMutexedString._align);
        
    
        return finalOut;
    }

    change(number) {
        wasm.OpaqueMutexedString_change(this.ffiValue, number);
    
        
        
    
    }

    borrow() {
        
        const diplomat_recieve_buffer = wasm.diplomat_alloc(OpaqueMutexedString._size, OpaqueMutexedString._align);
        
        // This lifetime edge depends on lifetimes 'a
        let aEdges = [this];
        const result = wasm.OpaqueMutexedString_borrow(diplomat_recieve_buffer, this.ffiValue);
    
        const finalOut = new OpaqueMutexedString(diplomat_recieve_buffer, aEdges);
        
        
        wasm.diplomat_free(diplomat_recieve_buffer, OpaqueMutexedString._size, OpaqueMutexedString._align);
        
    
        return finalOut;
    }

    static borrowOther(other) {
        
        const diplomat_recieve_buffer = wasm.diplomat_alloc(OpaqueMutexedString._size, OpaqueMutexedString._align);
        
        // This lifetime edge depends on lifetimes 'a
        let aEdges = [other];
        const result = wasm.OpaqueMutexedString_borrow_other(diplomat_recieve_buffer, other.ffiValue);
    
        const finalOut = new OpaqueMutexedString(diplomat_recieve_buffer, aEdges);
        
        
        wasm.diplomat_free(diplomat_recieve_buffer, OpaqueMutexedString._size, OpaqueMutexedString._align);
        
    
        return finalOut;
    }

    borrowSelfOrOther(other) {
        
        const diplomat_recieve_buffer = wasm.diplomat_alloc(OpaqueMutexedString._size, OpaqueMutexedString._align);
        
        // This lifetime edge depends on lifetimes 'a
        let aEdges = [this, other];
        const result = wasm.OpaqueMutexedString_borrow_self_or_other(diplomat_recieve_buffer, this.ffiValue, other.ffiValue);
    
        const finalOut = new OpaqueMutexedString(diplomat_recieve_buffer, aEdges);
        
        
        wasm.diplomat_free(diplomat_recieve_buffer, OpaqueMutexedString._size, OpaqueMutexedString._align);
        
    
        return finalOut;
    }

    getLenAndAdd(other) {
        const result = wasm.OpaqueMutexedString_get_len_and_add(this.ffiValue, other);
    
        const finalOut = result;
        
        
    
        return finalOut;
    }

    dummyStr() {
        
        // This lifetime edge depends on lifetimes 'a
        let aEdges = [this];
        const result = wasm.OpaqueMutexedString_dummy_str(this.ffiValue);
    
        const finalOut = result(aEdges) // TODO: Slice c_to_js;
        
        
    
        return finalOut;
    }

    wrapper() {
        
        const diplomat_recieve_buffer = wasm.diplomat_alloc(Utf16Wrap._size, Utf16Wrap._align);
        const result = wasm.OpaqueMutexedString_wrapper(diplomat_recieve_buffer, this.ffiValue);
    
        const finalOut = new Utf16Wrap(diplomat_recieve_buffer, []);
        
        
        wasm.diplomat_free(diplomat_recieve_buffer, Utf16Wrap._size, Utf16Wrap._align);
        
    
        return finalOut;
    }

    

}