// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs"
import * as diplomatRuntime from "./diplomat-runtime.mjs"



export class OptionOpaqueChar {
    

    get ffiValue(): pointer;


    assertChar(ch: char): void;

}