// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs"
import * as diplomatRuntime from "./diplomat-runtime.mjs"



export class RefList {
    

    get ffiValue(): pointer;


    static node(data: RefListParameter): RefList;

    

}