// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs"
import * as diplomatRuntime from "./diplomat-runtime.mjs"


const RefListParameter_box_destroy_registry = new FinalizationRegistry((ptr) => {
	wasm.RefListParameter_destroy(ptr);
});
export class RefListParameter {
	// Internal ptr reference:
	#ptr = null;

	// Lifetimes are only to keep dependencies alive.
	#selfEdge = [];
	
	
	constructor(ptr, selfEdge) {
		
		this.#ptr = ptr;
		this.#selfEdge = selfEdge;
		if (this.#selfEdge.length === 0) {
			// TODO: Do we need owned? Should double check with Dart opaque types.
			RefListParameter_box_destroy_registry.register(this, this.#ptr);
		}
	}

}