// generated by diplomat-tool

import { ErrorEnum } from "./ErrorEnum.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";




const ResultOpaque_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.ResultOpaque_destroy(ptr);
});

export class ResultOpaque {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];
    
    
    constructor(ptr, selfEdge) {
        
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;
        // Unconditionally register to destroy when this object is ready to garbage collect.
        ResultOpaque_box_destroy_registry.register(this, this.#ptr);
    }

    get ffiValue() {
        return this.#ptr;
    }


    static new_(i) {
        
        const diplomat_recieve_buffer = wasm.diplomat_alloc(5, 4);
        const result = wasm.ResultOpaque_new(diplomat_recieve_buffer, i);
    
        if (!diplomatRuntime.resultFlag(wasm, diplomat_recieve_buffer), resultByte) {
            throw ErrorEnum[Array.from(ErrorEnum.values.keys())[diplomat_recieve_buffer.union.error]];
        }
        const finalOut = new ResultOpaque(diplomat_recieve_buffer.union.ok, []);
        
        
        wasm.diplomat_free(diplomat_recieve_buffer, 5, 4);
        
    
        return finalOut;
    }

    static newFailingFoo() {
        
        const diplomat_recieve_buffer = wasm.diplomat_alloc(5, 4);
        const result = wasm.ResultOpaque_new_failing_foo(diplomat_recieve_buffer);
    
        if (!diplomatRuntime.resultFlag(wasm, diplomat_recieve_buffer), resultByte) {
            throw ErrorEnum[Array.from(ErrorEnum.values.keys())[diplomat_recieve_buffer.union.error]];
        }
        const finalOut = new ResultOpaque(diplomat_recieve_buffer.union.ok, []);
        
        
        wasm.diplomat_free(diplomat_recieve_buffer, 5, 4);
        
    
        return finalOut;
    }

    static newFailingBar() {
        
        const diplomat_recieve_buffer = wasm.diplomat_alloc(5, 4);
        const result = wasm.ResultOpaque_new_failing_bar(diplomat_recieve_buffer);
    
        if (!diplomatRuntime.resultFlag(wasm, diplomat_recieve_buffer), resultByte) {
            throw ErrorEnum[Array.from(ErrorEnum.values.keys())[diplomat_recieve_buffer.union.error]];
        }
        const finalOut = new ResultOpaque(diplomat_recieve_buffer.union.ok, []);
        
        
        wasm.diplomat_free(diplomat_recieve_buffer, 5, 4);
        
    
        return finalOut;
    }

    static newFailingUnit() {
        
        const diplomat_recieve_buffer = wasm.diplomat_alloc(5, 4);
        const result = wasm.ResultOpaque_new_failing_unit(diplomat_recieve_buffer);
    
        if (!diplomatRuntime.resultFlag(wasm, diplomat_recieve_buffer), resultByte) {
            return null;
        }
        const finalOut = new ResultOpaque(diplomat_recieve_buffer.union.ok, []);
        
        
        wasm.diplomat_free(diplomat_recieve_buffer, 5, 4);
        
    
        return finalOut;
    }

    static newFailingStruct(i) {
        
        const diplomat_recieve_buffer = wasm.diplomat_alloc(5, 4);
        const result = wasm.ResultOpaque_new_failing_struct(diplomat_recieve_buffer, i);
    
        if (!diplomatRuntime.resultFlag(wasm, diplomat_recieve_buffer), resultByte) {
            throw new ErrorStruct(diplomat_recieve_buffer.union.error);
        }
        const finalOut = new ResultOpaque(diplomat_recieve_buffer.union.ok, []);
        
        
        wasm.diplomat_free(diplomat_recieve_buffer, 5, 4);
        
    
        return finalOut;
    }

    static newInErr(i) {
        const result = wasm.ResultOpaque_new_in_err(i);
    
        if (!diplomatRuntime.resultFlag(wasm, result), resultByte) {
            throw new ResultOpaque(result.union.error, []);
        }
    
        
        
    
        return finalOut;
    }

    static newInt(i) {
        
        const diplomat_recieve_buffer = wasm.diplomat_alloc(5, 4);
        const result = wasm.ResultOpaque_new_int(diplomat_recieve_buffer, i);
    
        if (!diplomatRuntime.resultFlag(wasm, diplomat_recieve_buffer), resultByte) {
            return null;
        }
        const finalOut = diplomat_recieve_buffer.union.ok;
        
        
        wasm.diplomat_free(diplomat_recieve_buffer, 5, 4);
        
    
        return finalOut;
    }

    static newInEnumErr(i) {
        
        const diplomat_recieve_buffer = wasm.diplomat_alloc(5, 4);
        const result = wasm.ResultOpaque_new_in_enum_err(diplomat_recieve_buffer, i);
    
        if (!diplomatRuntime.resultFlag(wasm, diplomat_recieve_buffer), resultByte) {
            throw new ResultOpaque(diplomat_recieve_buffer.union.error, []);
        }
        const finalOut = ErrorEnum[Array.from(ErrorEnum.values.keys())[diplomat_recieve_buffer.union.ok]];
        
        
        wasm.diplomat_free(diplomat_recieve_buffer, 5, 4);
        
    
        return finalOut;
    }

    assertInteger(i) {
        wasm.ResultOpaque_assert_integer(this.ffiValue, i);
    
        
        
    
    }

    

}