// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs"
import * as diplomatRuntime from "./diplomat-runtime.mjs"


const Two_box_destroy_registry = new FinalizationRegistry((ptr) => {
	wasm.Two_destroy(ptr);
});
export class Two {
	

}