// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs"
import * as diplomatRuntime from "./diplomat-runtime.mjs"


const Unnamespaced_box_destroy_registry = new FinalizationRegistry((ptr) => {
	wasm.namespace_Unnamespaced_destroy(ptr);
});
export class Unnamespaced {
	

	static make(e:AttrEnum): Unnamespaced;

	useNamespaced(n:AttrOpaque1): void;

}