// generated by diplomat-tool

import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";




const Utf16Wrap_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.Utf16Wrap_destroy(ptr);
});

export class Utf16Wrap {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];
    
    
    _fromFFI(ptr, selfEdge) {
        
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;
        // Unconditionally register to destroy when this object is ready to garbage collect.
        Utf16Wrap_box_destroy_registry.register(this, this.#ptr);
    }
    constructor() {
        throw new Error("You cannot create the opaque type Utf16Wrap without a valid constructor. You may call one of the static methods below, or you may label the default opaque constructor in the diplomat FFI definition with #[diplomat::attr(constructor)].");
    }

    get ffiValue() {
        return this.#ptr;
    }


    borrowCont() {
        
        const diplomat_receive_buffer = wasm.diplomat_alloc(8, 4);
        
        // This lifetime edge depends on lifetimes 'a
        let aEdges = [this];
        const result = wasm.Utf16Wrap_borrow_cont(diplomat_receive_buffer, this.ffiValue);
    
        try {
    
            return diplomat_receive_buffer(aEdges) // TODO: Slice c_to_js;
        } finally {
        
            wasm.diplomat_free(diplomat_receive_buffer, 8, 4);
        
        }
    }

    owned() {
        
        const diplomat_receive_buffer = wasm.diplomat_alloc(8, 4);
        const result = wasm.Utf16Wrap_owned(diplomat_receive_buffer, this.ffiValue);
    
        try {
    
            return diplomat_receive_buffer // TODO: Slice c_to_js;
        } finally {
        
            wasm.diplomat_free(diplomat_receive_buffer, 8, 4);
        
        }
    }

    

}