
// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs"
import * as diplomatRuntime from "./diplomat-runtime.mjs"




export class Utf16Wrap {
    

    get ffiValue(): pointer;


    borrowCont(): String;

    owned(): String;

    

}