// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs"
import * as diplomatRuntime from "./diplomat-runtime.mjs"


export class Utf16Wrap {
	
	
	borrowCont() {
        const result = wasm.Utf16Wrap_borrow_cont();
        return result(aEdges) // TODO;
    }
	
	owned() {
        const result = wasm.Utf16Wrap_owned();
        return result // TODO;
    }
	
}