// generated by diplomat-tool
import type { Foo } from "./Foo"
import type { pointer, codepoint, DiplomatSliceStr, DiplomatSliceStrings, DiplomatSlicePrimitive } from "./diplomat-runtime.d.ts";

export class Bar {
    

    get ffiValue(): pointer;

    get foo(): Foo;
}