// generated by diplomat-tool
import type { ScalarPairWithPadding } from "./ScalarPairWithPadding"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";


/** Testing JS-specific layout/padding behavior
*/
export class BigStructWithStuff {

    get first() : number;
    set first(value: number); 

    get second() : number;
    set second(value: number); 

    get third() : number;
    set third(value: number); 

    get fourth() : ScalarPairWithPadding;
    set fourth(value: ScalarPairWithPadding); 

    get fifth() : number;
    set fifth(value: number); 
    constructor(first: number, second: number, third: number, fourth: ScalarPairWithPadding, fifth: number);

    assertValue(): void;
}