// generated by diplomat-tool
import type { ScalarPairWithPadding } from "./ScalarPairWithPadding"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";


/** Testing JS-specific layout/padding behavior
*/
type BigStructWithStuff_Obj = {
    first: number;
    second: number;
    third: number;
    fourth: ScalarPairWithPadding;
    fifth: number;
};

export class BigStructWithStuff {

    get first() : number;
    set first(value: number); 

    get second() : number;
    set second(value: number); 

    get third() : number;
    set third(value: number); 

    get fourth() : ScalarPairWithPadding;
    set fourth(value: ScalarPairWithPadding); 

    get fifth() : number;
    set fifth(value: number); 
    constructor(structObj : BigStructWithStuff_Obj);

    assertValue(extraVal: number): void;
}