// generated by diplomat-tool
import type { pointer, codepoint, DiplomatSliceStr, DiplomatSliceStrings, DiplomatSlicePrimitive } from "./diplomat-runtime.d.ts";

export class BorrowedFieldsReturning {

    get bytes() : string;
    set bytes(value: string); 

}