// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class ContiguousEnum {
	
    constructor(value : ContiguousEnum | string);


    static FromValue(value : ContiguousEnum | string) : ContiguousEnum; 

    get value() : string;

    get ffiValue() : number;

    static C : ContiguousEnum;
    static D : ContiguousEnum;
    static E : ContiguousEnum;
    static F : ContiguousEnum;

}