// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

// Base enumerator definition
export class ContiguousEnum {
    constructor(value : ContiguousEnum | string);

    get value() : string;

    get ffiValue() : number;

    static C : ContiguousEnum;
    static D : ContiguousEnum;
    static E : ContiguousEnum;
    static F : ContiguousEnum;
}