// generated by diplomat-tool
import type { CyclicStructA } from "./CyclicStructA"
import type { CyclicStructA_Obj } from "./CyclicStructA"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

type CyclicStructC_Obj = {
    a: CyclicStructA_Obj;
};

export class CyclicStructC {

    get a() : CyclicStructA;
    set a(value: CyclicStructA); 
    constructor(structObj : CyclicStructC_Obj);

    static takesNestedParameters(c: CyclicStructC_Obj): CyclicStructC;

    cyclicOut(): string;
}