// generated by diplomat-tool
import type { CyclicStructB } from "./CyclicStructB"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

type CyclicStructA_Obj = {
    a: CyclicStructB;
};

export class CyclicStructA {

    get a() : CyclicStructB;
    set a(value: CyclicStructB); 
    constructor(structObj : CyclicStructA_Obj);

    static getB(): CyclicStructB;
}