// generated by diplomat-tool
import type { CyclicStructB } from "./CyclicStructB"
import type { CyclicStructB_obj } from "./CyclicStructB"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

type CyclicStructA_obj = {
    a: CyclicStructB_obj;
};



export class CyclicStructA {
	

    get a() : CyclicStructB;
    set a(value: CyclicStructB); 

    
    constructor(structObj : CyclicStructA_obj);


    static getB(): CyclicStructB;

    cyclicOut(): string;
}