// generated by diplomat-tool
import type { UnimportedEnum } from "./UnimportedEnum"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

export class ImportedStruct {

    get foo() : UnimportedEnum;
    set foo(value: UnimportedEnum); 

    get count() : number;
    set count(value: number); 
    constructor(foo,count) {
        if (arguments.length > 0 && arguments[0] === diplomatRuntime.internalConstructor) {
            this.#fromFFI(arguments.slice(1));
        } else {
            
            this.#foo = foo;
            
            this.#count = count;
            
        }}
    

}