// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class MyEnum {
    

    static fromValue(value : MyEnum | string) : MyEnum; 

    get value() : string;

    get ffiValue() : number;

    static A : MyEnum;
    static B : MyEnum;
    static C : MyEnum;
    static D : MyEnum;
    static E : MyEnum;
    static F : MyEnum;

    intoValue(): number;

    static getA(): MyEnum;

    constructor(value: MyEnum | string );
}