// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

export class MyZst {
    constructor(struct_obj) {
        if (typeof struct_obj !== "object") {
            throw new Error("MyZst's constructor takes an object of MyZst's fields.");
        }

    }

}