// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class OptionEnum {
	
    constructor(value : OptionEnum | number);

    static FromValue(value : OptionEnum | number) : OptionEnum; 

    get value() : string;

    get ffiValue() : number;

    static Foo : OptionEnum;
    static Bar : OptionEnum;
}