// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class OptionEnum {
	
    constructor(value : OptionEnum | string);


    static FromValue(value : OptionEnum | string) : OptionEnum; 

    get value() : string;

    get ffiValue() : number;

    static Foo : OptionEnum;
    static Bar : OptionEnum;

}