// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

// Base enumerator definition
export class OptionEnum {
    #value = undefined;

    static values = new Map([
        ["Foo", 0],
        ["Bar", 1]
    ]);

    constructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            this.#value = arguments[1];
            return;
        }

        if (value instanceof OptionEnum) {
            this.#value = value.value;
            return;
        }

        let intVal = OptionEnum.values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal == null) {
            this.#value = intVal;
            return;
        }

        throw TypeError(value + " is not a OptionEnum and does not correspond to any of its enumerator values.");
    }

    get value() {
        return [...OptionEnum.values.keys()][this.#value];
    }

    get ffiValue() {
        return this.#value;
    }

    static Foo = new OptionEnum(diplomatRuntime.internalConstructor, 0);
    static Bar = new OptionEnum(diplomatRuntime.internalConstructor, 1);
}