// generated by diplomat-tool
import type { RenamedMyIterator } from "./RenamedMyIterator"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

export class RenamedMyIterable {
    

    get ffiValue(): pointer;
    static new_(x: Array<number>): RenamedMyIterable;

    [Symbol.iterator](): RenamedMyIterator;

    

}