// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

export type RenamedVectorTest_obj = {
    test: number;
};



export class RenamedVectorTest {
    get test(): number;
    set test(value: number);
    /** @internal */
    static fromFields(structObj : RenamedVectorTest_obj) : RenamedVectorTest;

    /**
    * Create `RenamedVectorTest` from an object that contains all of `RenamedVectorTest`s fields.
    * Optional fields do not need to be included in the provided object.
    */
    constructor(structObj: RenamedVectorTest_obj);


    static new_(): RenamedVectorTest;
}