// generated by diplomat-tool
import { RenamedOpaqueIterator } from "./RenamedOpaqueIterator.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const RenamedOpaqueIterable_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.namespace_OpaqueIterable_destroy(ptr);
});

export class RenamedOpaqueIterable {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("RenamedOpaqueIterable is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            RenamedOpaqueIterable_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    #defaultConstructor(size) {

        const result = wasm.namespace_OpaqueIterable_new(size);

        try {
            return new RenamedOpaqueIterable(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    [Symbol.iterator]() {
        // This lifetime edge depends on lifetimes 'a
        let aEdges = [this];


        const result = wasm.namespace_OpaqueIterable_iter(this.ffiValue);

        try {
            return new RenamedOpaqueIterator(diplomatRuntime.internalConstructor, result, [], aEdges);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    constructor(size) {
        if (arguments[0] === diplomatRuntime.exposeConstructor) {
            return this.#internalConstructor(...Array.prototype.slice.call(arguments, 1));
        } else if (arguments[0] === diplomatRuntime.internalConstructor) {
            return this.#internalConstructor(...arguments);
        } else {
            return this.#defaultConstructor(...arguments);
        }
    }
}