// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class RenamedAttrEnum {
	
    constructor(value : RenamedAttrEnum | string);

    get value() : string;

    get ffiValue() : number;

    static A : RenamedAttrEnum;
    static B : RenamedAttrEnum;
    static Renamed : RenamedAttrEnum;

}