// generated by diplomat-tool
import type { pointer, codepoint, DiplomatSliceStr, DiplomatSliceStrings, DiplomatSlicePrimitive } from "./diplomat-runtime.d.ts";

export class RenamedAttrOpaque2 {
    

    get ffiValue(): pointer;
}