// generated by diplomat-tool
import type { pointer, char } from "./diplomat-runtime.d.ts";

export class RenamedMyIterator {
    

    get ffiValue(): pointer;


    #iteratorNext(): number | null;

    
    next() : number;

}