// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class RenamedAttrEnum {

    /** @internal */
    static fromValue(value: RenamedAttrEnum | string): RenamedAttrEnum;

    get value(): string;

    /** @internal */
    get ffiValue(): number;

    static A : RenamedAttrEnum;
    static B : RenamedAttrEnum;
    static Renamed : RenamedAttrEnum;


    constructor(value: RenamedAttrEnum | string );
}