// generated by diplomat-tool
import type { AttrOpaque1Renamed } from "./AttrOpaque1Renamed"
import type { pointer, char } from "./diplomat-runtime.d.ts";

export class RenamedOpaqueIterator {
    

    get ffiValue(): pointer;


    #iteratorNext(): AttrOpaque1Renamed | null;

    
    next() : IteratorResult<AttrOpaque1Renamed>;

}