// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";


/** Testing JS-specific layout/padding behavior
*/
type ScalarPairWithPadding_Obj = {
    first: number;
    second: number;
};

export class ScalarPairWithPadding {

    get first() : number;
    set first(value: number); 

    get second() : number;
    set second(value: number); 
    constructor(struct_obj : ScalarPairWithPadding_Obj);

    assertValue(): void;
}