// generated by diplomat-tool
import { Opaque } from "./Opaque.mjs"
import { OpaqueMut } from "./OpaqueMut.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



export class StructOfOpaque {
    #i;
    get i() {
        return this.#i;
    }
    set i(value){
        this.#i = value;
    }
    #j;
    get j() {
        return this.#j;
    }
    set j(value){
        this.#j = value;
    }
    /** @internal */
    static fromFields(structObj) {
        return new StructOfOpaque(structObj);
    }

    #internalConstructor(structObj) {
        if (typeof structObj !== "object") {
            throw new Error("StructOfOpaque's constructor takes an object of StructOfOpaque's fields.");
        }

        if ("i" in structObj) {
            this.#i = structObj.i;
        } else {
            throw new Error("Missing required field i.");
        }

        if ("j" in structObj) {
            this.#j = structObj.j;
        } else {
            throw new Error("Missing required field j.");
        }

        return this;
    }

    // Return this struct in FFI function friendly format.
    // Returns an array that can be expanded with spread syntax (...)// If this struct contains any slices, their lifetime-edge-relevant information will be
    // set up here, and can be appended to any relevant lifetime arrays here. <lifetime>AppendArray accepts a list
    // of arrays for each lifetime to do so. It accepts multiple lists per lifetime in case the caller needs to tie a lifetime to multiple
    // output arrays. Null is equivalent to an empty list: this lifetime is not being borrowed from.
    _intoFFI(
        dst,
        functionCleanupArena,
        appendArrayMap
    ) {

        this._writeToArrayBuffer(wasm.memory.buffer, dst, functionCleanupArena, appendArrayMap);

        return dst;
    }

    static get _sizeBytes() {
        return 8;
    }

    /// Currently unused, we may want to use later on though:
    static get _sizeAlign() {
        return 4;
    }

    static _fromSuppliedValue(internalConstructor, obj) {
        if (internalConstructor !== diplomatRuntime.internalConstructor) {
            throw new Error("_fromSuppliedValue cannot be called externally.");
        }

        if (obj instanceof StructOfOpaque) {
            return obj;
        }

        return StructOfOpaque.fromFields(obj);
    }

    _writeToArrayBuffer(
        arrayBuffer,
        offset,
        functionCleanupArena,
        appendArrayMap
    ) {
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 0, this.#i.ffiValue, Uint32Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 4, this.#j.ffiValue, Uint32Array);
    }

    static _fromFFI(internalConstructor, ptr, aEdges) {
        if (internalConstructor !== diplomatRuntime.internalConstructor) {
            throw new Error("StructOfOpaque._fromFFI is not meant to be called externally. Please use the default constructor.");
        }
        let structObj = {};
        const iDeref = diplomatRuntime.ptrRead(wasm, ptr);
        structObj.i = new Opaque(diplomatRuntime.internalConstructor, iDeref, aEdges);
        const jDeref = diplomatRuntime.ptrRead(wasm, ptr + 4);
        structObj.j = new OpaqueMut(diplomatRuntime.internalConstructor, jDeref, aEdges);

        return new StructOfOpaque(structObj);
    }

    // Return all fields corresponding to lifetime `'a`
    // without handling lifetime dependencies (this is the job of the caller)
    // This is all fields that may be borrowed from if borrowing `'a`,
    // assuming that there are no `'other: a`. bounds. In case of such bounds,
    // the caller should take care to also call _fieldsForLifetimeOther
    get _fieldsForLifetimeA() {
        return [this.#i, this.#j];
    };


    constructor(structObj) {
        return this.#internalConstructor(...arguments)
    }
}