// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class UnimportedEnum {
	
    constructor(value : UnimportedEnum | number);

    static FromValue(value : UnimportedEnum | number) : UnimportedEnum; 

    get value() : string;

    get ffiValue() : number;

    static A : UnimportedEnum;
    static B : UnimportedEnum;
    static C : UnimportedEnum;
}