// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

// Base enumerator definition
export class UnimportedEnum {
    constructor(value : UnimportedEnum | string);

    get value() : string;

    get ffiValue() : number;
}