// generated by diplomat-tool
import type { AttrOpaque1Renamed } from "./AttrOpaque1Renamed"
import type { RenamedAttrEnum } from "./RenamedAttrEnum"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class Unnamespaced {
    
    get ffiValue(): pointer;

    static make(e: RenamedAttrEnum): Unnamespaced;

    useNamespaced(n: AttrOpaque1Renamed): void;
}