// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class Bar implements ffi.Finalizable {
  final ffi.Pointer<ffi.Opaque> _ffi;

  // These are "used" in the sense that they keep dependencies alive
  // ignore: unused_field
  final core.List<Object> _selfEdge;
  // ignore: unused_field
  final core.List<Object> _bEdge;
  // ignore: unused_field
  final core.List<Object> _aEdge;

  // This takes in a list of lifetime edges (including for &self borrows)
  // corresponding to data this may borrow from. These should be flat arrays containing
  // references to objects, and this object will hold on to them to keep them alive and
  // maintain borrow validity.
  Bar._fromFfi(this._ffi, this._selfEdge, this._bEdge, this._aEdge) {
    if (_selfEdge.isEmpty) {
      _finalizer.attach(this, _ffi.cast());
    }
  }

  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(_Bar_destroy));

  Foo get foo {
    // This lifetime edge depends on lifetimes: 'b, 'a
    core.List<Object> bEdges = [this];
    // This lifetime edge depends on lifetimes: 'a
    core.List<Object> aEdges = [this];
    final result = _Bar_foo(_ffi);
    return Foo._fromFfi(result, bEdges, aEdges);
  }
}

@_DiplomatFfiUse('Bar_destroy')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'Bar_destroy')
// ignore: non_constant_identifier_names
external void _Bar_destroy(ffi.Pointer<ffi.Void> self);

@_DiplomatFfiUse('Bar_foo')
@ffi.Native<ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'Bar_foo')
// ignore: non_constant_identifier_names
external ffi.Pointer<ffi.Opaque> _Bar_foo(ffi.Pointer<ffi.Opaque> self);

// dart format on
