// generated by diplomat-tool

part of 'lib.g.dart';

final class _BorrowedFieldsReturningFfi extends ffi.Struct {
  external _SliceUtf8 bytes;
}

final class BorrowedFieldsReturning {
  String bytes;
  // ignore: unused_field
  final core.List<Object> _edgeA;

  BorrowedFieldsReturning({required this.bytes}) : _edgeA = [];

  // Internal constructor from FFI.
  // This struct contains borrowed fields, so this takes in a list of
  // "edges" corresponding to where each lifetime's data may have been borrowed from
  // and passes it down to individual fields containing the borrow.
  // This method does not attempt to handle any dependencies between lifetimes, the caller
  // should handle this when constructing edge arrays.
  // ignore: unused_element
  BorrowedFieldsReturning._(_BorrowedFieldsReturningFfi underlying, {required core.List<Object> edgeA}) :
    _edgeA = edgeA,
    bytes = Utf8Decoder().convert(underlying.bytes._pointer.asTypedList(underlying.bytes._length));

  // ignore: unused_element
  _BorrowedFieldsReturningFfi _pointer(ffi.Allocator temp) {
    final struct = ffi.Struct.create<_BorrowedFieldsReturningFfi>();
    final bytesView = bytes.utf8View;
    struct.bytes._pointer = bytesView.pointer(temp);
    struct.bytes._length = bytesView.length;
    return struct;
  }

  @override
  bool operator ==(Object other) =>
      other is BorrowedFieldsReturning &&
      other.bytes == this.bytes;

  @override
  int get hashCode => Object.hashAll([
        this.bytes,
      ]);
}
