// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class _ContainingTupleFfi extends ffi.Struct {
  external _TupleStructFfi inner;
}

final class ContainingTuple {
  // ignore: public_member_api_docs
  TupleStruct inner;

  // ignore: public_member_api_docs
  ContainingTuple({required this.inner});

  // ignore: unused_element
  ContainingTuple._fromFfi(_ContainingTupleFfi ffi, core.List<Object> aEdges) :
    inner = TupleStruct._fromFfi(ffi.inner, aEdges);

  // If this struct contains any slices, their lifetime-edge-relevant objects (typically _FinalizedArenas) will only
  // be constructed here, and can be appended to any relevant lifetime arrays here. <lifetime>AppendArray accepts a list
  // of arrays for each lifetime to do so. It accepts multiple lists per lifetime in case the caller needs to tie a lifetime to multiple
  // output arrays. Null is equivalent to an empty list: this lifetime is not being borrowed from.
  // ignore: unused_element
  _ContainingTupleFfi _toFfi(ffi.Allocator temp, {core.List<core.List<Object>> aAppendArray = const []}) {
    final struct = ffi.Struct.create<_ContainingTupleFfi>();
    struct.inner = inner._toFfi(temp, aAppendArray: [...aAppendArray]);
    return struct;
  }


  @override
  bool operator ==(Object other) =>
      other is ContainingTuple &&
      other.inner == inner;

  @override
  int get hashCode => Object.hashAll([
        inner,
      ]);

  // Return all fields corresponding to lifetime `'a`
  // without handling lifetime dependencies (this is the job of the caller)
  // This is all fields that may be borrowed from if borrowing `'a`,
  // assuming that there are no `'other: a`. bounds. In case of such bounds,
  // the caller should take care to also call _fieldsForLifetimeOther
  // ignore: unused_element
  core.List<Object> get _fieldsForLifetimeA => [...inner._fieldsForLifetimeA];
}

// dart format on
