// generated by diplomat-tool

part of 'lib.g.dart';

final class _CyclicStructCFfi extends ffi.Struct {
  external _CyclicStructAFfi a;
}

final class CyclicStructC {
  CyclicStructA a;

  CyclicStructC({required this.a});

  // This struct contains borrowed fields, so this takes in a list of
  // "edges" corresponding to where each lifetime's data may have been borrowed from
  // and passes it down to individual fields containing the borrow.
  // This method does not attempt to handle any dependencies between lifetimes, the caller
  // should handle this when constructing edge arrays.
  // ignore: unused_element
  CyclicStructC._fromFfi(_CyclicStructCFfi ffi) :
    a = CyclicStructA._fromFfi(ffi.a);

  // ignore: unused_element
  _CyclicStructCFfi _toFfi(ffi.Allocator temp) {
    final struct = ffi.Struct.create<_CyclicStructCFfi>();
    struct.a = a._toFfi(temp);
    return struct;
  }

  String cyclicOut() {
    final temp = _FinalizedArena();
    final write = _Write();
    _CyclicStructC_cyclic_out(_toFfi(temp.arena), write._ffi);
    return write.finalize();
  }


  @override
  bool operator ==(Object other) =>
      other is CyclicStructC &&
      other.a == a;

  @override
  int get hashCode => Object.hashAll([
        a,
      ]);
}

@meta.RecordUse()
@ffi.Native<ffi.Void Function(_CyclicStructCFfi, ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'CyclicStructC_cyclic_out')
// ignore: non_constant_identifier_names
external void _CyclicStructC_cyclic_out(_CyclicStructCFfi self, ffi.Pointer<ffi.Opaque> write);


