// generated by diplomat-tool

part of 'lib.g.dart';

final class _ImportedStructFfi extends ffi.Struct {
  @ffi.Int32()
  external int foo;
  @ffi.Uint8()
  external int count;
}

final class ImportedStruct {
  UnimportedEnum foo;
  int count;

  ImportedStruct({required this.foo, required this.count});

  // This struct contains borrowed fields, so this takes in a list of
  // "edges" corresponding to where each lifetime's data may have been borrowed from
  // and passes it down to individual fields containing the borrow.
  // This method does not attempt to handle any dependencies between lifetimes, the caller
  // should handle this when constructing edge arrays.
  // ignore: unused_element
  ImportedStruct._fromFfi(_ImportedStructFfi ffi) :
    foo = UnimportedEnum.values[ffi.foo],
    count = ffi.count;

  // ignore: unused_element
  _ImportedStructFfi _toFfi(ffi.Allocator temp) {
    final struct = ffi.Struct.create<_ImportedStructFfi>();
    struct.foo = foo.index;
    struct.count = count;
    return struct;
  }

  @override
  bool operator ==(Object other) =>
      other is ImportedStruct &&
      other.foo == this.foo &&
      other.count == this.count;

  @override
  int get hashCode => Object.hashAll([
        this.foo,
        this.count,
      ]);
}
