// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class OpaqueMut implements ffi.Finalizable {
  final ffi.Pointer<ffi.Opaque> _ffi;

  // These are "used" in the sense that they keep dependencies alive
  // ignore: unused_field
  final core.List<Object> _selfEdge;

  // This takes in a list of lifetime edges (including for &self borrows)
  // corresponding to data this may borrow from. These should be flat arrays containing
  // references to objects, and this object will hold on to them to keep them alive and
  // maintain borrow validity.
  OpaqueMut._fromFfi(this._ffi, this._selfEdge) {
    if (_selfEdge.isEmpty) {
      _finalizer.attach(this, _ffi.cast());
    }
  }

  @_DiplomatFfiUse('OpaqueMut_destroy')
  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(_OpaqueMut_destroy));

  factory OpaqueMut() {
    final result = _OpaqueMut_new();
    return OpaqueMut._fromFfi(result, []);
  }

}

@_DiplomatFfiUse('OpaqueMut_destroy')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'OpaqueMut_destroy')
// ignore: non_constant_identifier_names
external void _OpaqueMut_destroy(ffi.Pointer<ffi.Void> self);

@_DiplomatFfiUse('OpaqueMut_new')
@ffi.Native<ffi.Pointer<ffi.Opaque> Function()>(isLeaf: true, symbol: 'OpaqueMut_new')
// ignore: non_constant_identifier_names
external ffi.Pointer<ffi.Opaque> _OpaqueMut_new();

// dart format on
