// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

enum OptionEnum {
  // ignore: public_member_api_docs
  foo,
  // ignore: public_member_api_docs
  bar,
  // ignore: public_member_api_docs
  baz;

}

// dart format on
