// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class RenamedMyIterator implements ffi.Finalizable, core.Iterator<int> {
  final ffi.Pointer<ffi.Opaque> _ffi;

  // These are "used" in the sense that they keep dependencies alive
  // ignore: unused_field
  final core.List<Object> _selfEdge;
  // ignore: unused_field
  final core.List<Object> _aEdge;

  // This takes in a list of lifetime edges (including for &self borrows)
  // corresponding to data this may borrow from. These should be flat arrays containing
  // references to objects, and this object will hold on to them to keep them alive and
  // maintain borrow validity.
  RenamedMyIterator._fromFfi(this._ffi, this._selfEdge, this._aEdge) {
    if (_selfEdge.isEmpty) {
      _finalizer.attach(this, _ffi.cast());
    }
  }

  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(_namespace_MyIterator_destroy));

  int? _current;

  @override
  int get current => _current!;

  @override
  bool moveNext() {
    _current = _iteratorNext();
    return _current != null;
  }

  int? _iteratorNext() {
    final result = _namespace_MyIterator_next(_ffi);
    if (!result.isOk) {
      return null;
    }
    return result.union.ok;
  }
}

@_DiplomatFfiUse('namespace_MyIterator_destroy')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'namespace_MyIterator_destroy')
// ignore: non_constant_identifier_names
external void _namespace_MyIterator_destroy(ffi.Pointer<ffi.Void> self);

@_DiplomatFfiUse('namespace_MyIterator_next')
@ffi.Native<_ResultUint8Void Function(ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'namespace_MyIterator_next')
// ignore: non_constant_identifier_names
external _ResultUint8Void _namespace_MyIterator_next(ffi.Pointer<ffi.Opaque> self);

// dart format on
