// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class RenamedOpaqueZSTIndexer implements ffi.Finalizable {
  final ffi.Pointer<ffi.Opaque> _ffi;

  // These are "used" in the sense that they keep dependencies alive
  // ignore: unused_field
  final core.List<Object> _selfEdge;

  // This takes in a list of lifetime edges (including for &self borrows)
  // corresponding to data this may borrow from. These should be flat arrays containing
  // references to objects, and this object will hold on to them to keep them alive and
  // maintain borrow validity.
  RenamedOpaqueZSTIndexer._fromFfi(this._ffi, this._selfEdge) {
    if (_selfEdge.isEmpty) {
      _finalizer.attach(this, _ffi.cast());
    }
  }

  @_DiplomatFfiUse('namespace_OpaqueZSTIndexer_destroy')
  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(_namespace_OpaqueZSTIndexer_destroy));

  factory RenamedOpaqueZSTIndexer() {
    final result = _namespace_OpaqueZSTIndexer_new();
    return RenamedOpaqueZSTIndexer._fromFfi(result, []);
  }

  RenamedOpaqueZSTIndexer? operator [](int idx) {
    final result = _namespace_OpaqueZSTIndexer_index(_ffi, idx);
    return result.address == 0 ? null : RenamedOpaqueZSTIndexer._fromFfi(result, []);
  }

}

@_DiplomatFfiUse('namespace_OpaqueZSTIndexer_destroy')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'namespace_OpaqueZSTIndexer_destroy')
// ignore: non_constant_identifier_names
external void _namespace_OpaqueZSTIndexer_destroy(ffi.Pointer<ffi.Void> self);

@_DiplomatFfiUse('namespace_OpaqueZSTIndexer_new')
@ffi.Native<ffi.Pointer<ffi.Opaque> Function()>(isLeaf: true, symbol: 'namespace_OpaqueZSTIndexer_new')
// ignore: non_constant_identifier_names
external ffi.Pointer<ffi.Opaque> _namespace_OpaqueZSTIndexer_new();

@_DiplomatFfiUse('namespace_OpaqueZSTIndexer_index')
@ffi.Native<ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>, ffi.Size)>(isLeaf: true, symbol: 'namespace_OpaqueZSTIndexer_index')
// ignore: non_constant_identifier_names
external ffi.Pointer<ffi.Opaque> _namespace_OpaqueZSTIndexer_index(ffi.Pointer<ffi.Opaque> self, int idx);

// dart format on
