// ignore_for_file: experimental_member_use, unused_element
// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

enum RenamedAttrEnum {
  // ignore: public_member_api_docs
  a,
  // ignore: public_member_api_docs
  b,
  // ignore: public_member_api_docs
  renamed;

}

// dart format on
