// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class RenamedMixinTest implements ffi.Finalizable {
  final ffi.Pointer<ffi.Opaque> _ffi;

  // These are "used" in the sense that they keep dependencies alive
  // ignore: unused_field
  final core.List<Object> _selfEdge;

  // This takes in a list of lifetime edges (including for &self borrows)
  // corresponding to data this may borrow from. These should be flat arrays containing
  // references to objects, and this object will hold on to them to keep them alive and
  // maintain borrow validity.
  RenamedMixinTest._fromFfi(this._ffi, this._selfEdge) {
    if (_selfEdge.isEmpty) {
      _finalizer.attach(this, _ffi.cast());
    }
  }

  @_DiplomatFfiUse('namespace_MixinTest_destroy')
  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(_namespace_MixinTest_destroy));

  static String hello() {
    final write = _Write();
    _namespace_MixinTest_hello(write._ffi);
    return write.finalize();
  }

}

@_DiplomatFfiUse('namespace_MixinTest_destroy')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'namespace_MixinTest_destroy')
// ignore: non_constant_identifier_names
external void _namespace_MixinTest_destroy(ffi.Pointer<ffi.Void> self);

@_DiplomatFfiUse('namespace_MixinTest_hello')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'namespace_MixinTest_hello')
// ignore: non_constant_identifier_names
external void _namespace_MixinTest_hello(ffi.Pointer<ffi.Opaque> write);

// dart format on
