// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

/// Diplomat will prepend this whole block to the start of attrs.rs,
/// but we currently cannot do the same for proc_macro (until we hit MSRV >= 1.88).
/// So the workaround is to use the path to the module whenever referring to the imported type (as seen above).
final class RenamedNonMacroMixin {

  // ignore: public_member_api_docs
  RenamedNonMacroMixin();


  @override
  bool operator ==(Object other) =>
      other is RenamedNonMacroMixin;

  @override
  int get hashCode => 0;
}

// dart format on
