// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class _StructOfOpaqueFfi extends ffi.Struct {
  external ffi.Pointer<ffi.Opaque> i;
  external ffi.Pointer<ffi.Opaque> j;
}

final class StructOfOpaque {
  // ignore: public_member_api_docs
  Opaque i;
  // ignore: public_member_api_docs
  OpaqueMut j;

  // ignore: public_member_api_docs
  StructOfOpaque({required this.i, required this.j});

  // ignore: unused_element
  StructOfOpaque._fromFfi(_StructOfOpaqueFfi ffi, core.List<Object> aEdges) :
    i = Opaque._fromFfi(ffi.i, aEdges),
    j = OpaqueMut._fromFfi(ffi.j, aEdges);

  // If this struct contains any slices, their lifetime-edge-relevant objects (typically _FinalizedArenas) will only
  // be constructed here, and can be appended to any relevant lifetime arrays here. <lifetime>AppendArray accepts a list
  // of arrays for each lifetime to do so. It accepts multiple lists per lifetime in case the caller needs to tie a lifetime to multiple
  // output arrays. Null is equivalent to an empty list: this lifetime is not being borrowed from.
  // ignore: unused_element
  _StructOfOpaqueFfi _toFfi(ffi.Allocator temp, {core.List<core.List<Object>> aAppendArray = const []}) {
    final struct = ffi.Struct.create<_StructOfOpaqueFfi>();
    struct.i = i._ffi;
    struct.j = j._ffi;
    return struct;
  }


  @override
  bool operator ==(Object other) =>
      other is StructOfOpaque &&
      other.i == i &&
      other.j == j;

  @override
  int get hashCode => Object.hashAll([
        i,
        j,
      ]);

  // Return all fields corresponding to lifetime `'a`
  // without handling lifetime dependencies (this is the job of the caller)
  // This is all fields that may be borrowed from if borrowing `'a`,
  // assuming that there are no `'other: a`. bounds. In case of such bounds,
  // the caller should take care to also call _fieldsForLifetimeOther
  // ignore: unused_element
  core.List<Object> get _fieldsForLifetimeA => [i, j];
}

// dart format on
