// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class _TupleStructFfi extends ffi.Struct {
  @ffi.Int32()
  external int x;
  @ffi.Int32()
  external int y;
  external _MyStructFfi st;
  external ffi.Pointer<ffi.Opaque> op;
}

final class TupleStruct {
  // ignore: public_member_api_docs
  int x;
  // ignore: public_member_api_docs
  int y;
  // ignore: public_member_api_docs
  MyStruct st;
  // ignore: public_member_api_docs
  Opaque op;

  // ignore: public_member_api_docs
  TupleStruct({required this.x, required this.y, required this.st, required this.op});

  // ignore: unused_element
  TupleStruct._fromFfi(_TupleStructFfi ffi, core.List<Object> aEdges) :
    x = ffi.x,
    y = ffi.y,
    st = MyStruct._fromFfi(ffi.st),
    op = Opaque._fromFfi(ffi.op, aEdges);

  // If this struct contains any slices, their lifetime-edge-relevant objects (typically _FinalizedArenas) will only
  // be constructed here, and can be appended to any relevant lifetime arrays here. <lifetime>AppendArray accepts a list
  // of arrays for each lifetime to do so. It accepts multiple lists per lifetime in case the caller needs to tie a lifetime to multiple
  // output arrays. Null is equivalent to an empty list: this lifetime is not being borrowed from.
  // ignore: unused_element
  _TupleStructFfi _toFfi(ffi.Allocator temp, {core.List<core.List<Object>> aAppendArray = const []}) {
    final struct = ffi.Struct.create<_TupleStructFfi>();
    struct.x = x;
    struct.y = y;
    struct.st = st._toFfi(temp);
    struct.op = op._ffi;
    return struct;
  }

  static int takesStAsTuple(TupleStruct a) {
    final temp = _FinalizedArena();
    final result = _TupleStruct_takes_st_as_tuple(a._toFfi(temp.arena));
    return result;
  }

  static Rune takesContaining(ContainingTuple c) {
    final temp = _FinalizedArena();
    final result = _TupleStruct_takes_containing(c._toFfi(temp.arena));
    return result;
  }


  @override
  bool operator ==(Object other) =>
      other is TupleStruct &&
      other.x == x &&
      other.y == y &&
      other.st == st &&
      other.op == op;

  @override
  int get hashCode => Object.hashAll([
        x,
        y,
        st,
        op,
      ]);

  // Return all fields corresponding to lifetime `'a`
  // without handling lifetime dependencies (this is the job of the caller)
  // This is all fields that may be borrowed from if borrowing `'a`,
  // assuming that there are no `'other: a`. bounds. In case of such bounds,
  // the caller should take care to also call _fieldsForLifetimeOther
  // ignore: unused_element
  core.List<Object> get _fieldsForLifetimeA => [op];
}

@_DiplomatFfiUse('TupleStruct_takes_st_as_tuple')
@ffi.Native<ffi.Int32 Function(_TupleStructFfi)>(isLeaf: true, symbol: 'TupleStruct_takes_st_as_tuple')
// ignore: non_constant_identifier_names
external int _TupleStruct_takes_st_as_tuple(_TupleStructFfi a);

@_DiplomatFfiUse('TupleStruct_takes_containing')
@ffi.Native<ffi.Uint32 Function(_ContainingTupleFfi)>(isLeaf: true, symbol: 'TupleStruct_takes_containing')
// ignore: non_constant_identifier_names
external Rune _TupleStruct_takes_containing(_ContainingTupleFfi c);

// dart format on
