// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class Unnamespaced implements ffi.Finalizable {
  final ffi.Pointer<ffi.Opaque> _ffi;

  // These are "used" in the sense that they keep dependencies alive
  // ignore: unused_field
  final core.List<Object> _selfEdge;

  // This takes in a list of lifetime edges (including for &self borrows)
  // corresponding to data this may borrow from. These should be flat arrays containing
  // references to objects, and this object will hold on to them to keep them alive and
  // maintain borrow validity.
  Unnamespaced._fromFfi(this._ffi, this._selfEdge) {
    if (_selfEdge.isEmpty) {
      _finalizer.attach(this, _ffi.cast());
    }
  }

  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(_namespace_Unnamespaced_destroy));

  factory Unnamespaced.make(RenamedAttrEnum e) {
    final result = _namespace_Unnamespaced_make(e.index);
    return Unnamespaced._fromFfi(result, []);
  }

  void useNamespaced(AttrOpaque1Renamed n) {
    _namespace_Unnamespaced_use_namespaced(_ffi, n._ffi);
  }
}

@_DiplomatFfiUse('namespace_Unnamespaced_destroy')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'namespace_Unnamespaced_destroy')
// ignore: non_constant_identifier_names
external void _namespace_Unnamespaced_destroy(ffi.Pointer<ffi.Void> self);

@_DiplomatFfiUse('namespace_Unnamespaced_make')
@ffi.Native<ffi.Pointer<ffi.Opaque> Function(ffi.Int32)>(isLeaf: true, symbol: 'namespace_Unnamespaced_make')
// ignore: non_constant_identifier_names
external ffi.Pointer<ffi.Opaque> _namespace_Unnamespaced_make(int e);

@_DiplomatFfiUse('namespace_Unnamespaced_use_namespaced')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'namespace_Unnamespaced_use_namespaced')
// ignore: non_constant_identifier_names
external void _namespace_Unnamespaced_use_namespaced(ffi.Pointer<ffi.Opaque> self, ffi.Pointer<ffi.Opaque> n);

// dart format on
