// generated by diplomat-tool
import type { FixedDecimalGroupingStrategy } from "./FixedDecimalGroupingStrategy"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

type FixedDecimalFormatterOptions_obj = {
    groupingStrategy: FixedDecimalGroupingStrategy;
    someOtherConfig: boolean;
};

export class FixedDecimalFormatterOptions {

    get groupingStrategy() : FixedDecimalGroupingStrategy;
    set groupingStrategy(value: FixedDecimalGroupingStrategy); 

    get someOtherConfig() : boolean;
    set someOtherConfig(value: boolean); 
    constructor(structObj : FixedDecimalFormatterOptions_obj);

    static default_(): FixedDecimalFormatterOptions;
}