// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class FixedDecimalGroupingStrategy {
	
    constructor(value : FixedDecimalGroupingStrategy | number);

    static FromValue(value : FixedDecimalGroupingStrategy | number) : FixedDecimalGroupingStrategy; 

    get value() : string;

    get ffiValue() : number;

    static Auto : FixedDecimalGroupingStrategy;
    static Never : FixedDecimalGroupingStrategy;
    static Always : FixedDecimalGroupingStrategy;
    static Min2 : FixedDecimalGroupingStrategy;
}