// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class FixedDecimalGroupingStrategy {

    /** @internal */
    static fromValue(value: FixedDecimalGroupingStrategy | string): FixedDecimalGroupingStrategy;

    get value(): string;

    /** @internal */
    get ffiValue(): number;

    /**
     * Auto grouping
     */
    static Auto : FixedDecimalGroupingStrategy;
    /**
     * No grouping
     */
    static Never : FixedDecimalGroupingStrategy;
    /**
     * Always group
     */
    static Always : FixedDecimalGroupingStrategy;
    /**
     * At least 2 groups
     */
    static Min2 : FixedDecimalGroupingStrategy;


    constructor(value: FixedDecimalGroupingStrategy | string );
}