# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["wasm-demo-generator"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Load Rust toolchain for WASM.
        run: rustup target add wasm32-unknown-unknown
      # Cargo-make boilerplate
      - name: Get cargo-make version
        id: cargo-make-version
        run: |
          echo "::set-output name=hash::0.36.13"
        shell: bash
      - name: Attempt to load cached cargo-make
        uses: actions/cache@v2
        id: cargo-make-cache
        with:
          path: |
            ~/.cargo/bin/cargo-make
            ~/.cargo/bin/cargo-make.exe
          key: ${{ runner.os }}-make-${{ steps.cargo-make-version.outputs.hash }}
      - name: Install cargo-make
        if: steps.cargo-make-cache.outputs.cache-hit != 'true'
        uses: actions-rs/install@v0.1.2
        with:
          crate: cargo-make
          version: 0.36.13
      - name: Build page
        run: cargo make test-js2-example-app
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'example/js2/app/public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
